### ISSUE TITLE
to-do 리스트

### ISSUE THREAD

**Issue by ihatelua** [ihatelua/Gw#5]
- [x]  Http session 구현 : 타임리프로 구현해보기
- [ ] 전역에러처리 : 공통되는 exception 을 공통 layer 한곳에서 처리
- [ ] 메뉴관리 관리자메뉴 만들기
- [ ]
